---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logstash.name }}-certificate
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.logstash.name }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
   elasticsearch1.crt: |
     -----BEGIN CERTIFICATE-----
     MIIDCzCCAfOgAwIBAgIJAO3K4h+N9TBeMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
     BAMTB2Vsa2RlbW8wHhcNMjEwMTI5MDUxMjM1WhcNMjQwMTI5MDUxMjM1WjAZMRcw
     FQYDVQQDEw5lbGFzdGljc2VhcmNoMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
     AQoCggEBAJKn34fttLomy61fMts78bEwtfxiun7zXbue1FNcVJ2zUL3ZaSvqtyBF
     k7dwkGWSG6inOpnFpdwpvvmEcmUj/U2EFzalRi2Wd/ZznQ6BVC48Xr8oJa2Uh0Ug
     nCeB1ciniamkQxs4wWIxvAnYh97sSOi1YCb/ykfdeSxzz/aIZLIvBkRhxxnybb5n
     3TGqcsexed37ySVn4OfJ8FiWxBCQD3fn+7ch4Qtuhk8cE/CmujnkHAMj6YSNbRYT
     n+1EwLX9gIp6WaAR+0e1F1IXhdoLx7G3KLbfFgxG+q7fRsjeXvLg4xMPj4F6eJoH
     92PpOMfScjl2vXI3CL2n1j2vcrbiSLMCAwEAAaNdMFswHQYDVR0OBBYEFOmbRzWx
     pEXoxbJsN77Wa4I8oFhrMBkGA1UdEQQSMBCCDmVsYXN0aWNzZWFyY2gxMB8GA1Ud
     IwQYMBaAFCfBr1DfEnPg36E3FsdXGlGLXxeOMA0GCSqGSIb3DQEBCwUAA4IBAQCF
     IDDLD1rnr8TzupiO+xZsKtTPylK5D8wyMTtwAlSaaXBglRWyJhyapSB/tq8B0sJ7
     +04hhyKjPqZ0glr59KgOSF5ptmSJIV2cqFkFmPDn0OAlNfN2ddzS1dWb1Mq4/fVf
     sKGaslb5XKvV52plbuudrTk+BWMqoRz5kC2rRgl61ARk3L6aHNWhm3DOZBYFZHtU
     DC1CC6mKyvv1678GAI8f4BC6hGq7pb1Szv+1QSlu/+2OJdsB1z+I3jPtjL4HSadE
     j0FhO99r7cR/8ZCJcrdqvTRSVGcknwWkw78g7jpaZAKXlp/xNDP6A5xPVtvHWfHI
     MhqSFmdVa4kxPMNoa+9A
     -----END CERTIFICATE-----

   ca.crt: |
     -----BEGIN CERTIFICATE-----
     MIIC1jCCAb6gAwIBAgIJAOAgbsGNPp/9MA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
     BAMTB2Vsa2RlbW8wHhcNMjEwMTI5MDUxMTU4WhcNMjQwMTI5MDUxMTU4WjASMRAw
     DgYDVQQDEwdlbGtkZW1vMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
     oOjsOeDXix6CdnPq03XCHY4P8QxAUo8xoU2pdmPLXXKoMgjclTNK/FnUFNHF3elU
     cj+i7U3dS4kO7EzFx0/mkQI6lBNNUEN5m0peju3R6ibnzixnwnuzbtlIwZXygCBb
     tqHTnyGvn4t8n20SM0rz72Ebzdl4g8ejeL8AZxOHNjKnCnKMZIFqNub0qTwsEDIf
     1iYwhK6WyIkj96FYEIr/nGkZDM5MBOqtac7z+mzMWB6xe3ZSinRWgATjDuGI1Bm/
     iDKfjVktX2RA3hJNC3HFFAE1KYGuLOEoudbZ5Hy/elvv27DYysRhTuNtfv+hIteo
     EiwEctWozk1uxcgNKFjn/wIDAQABoy8wLTAdBgNVHQ4EFgQUJ8GvUN8Sc+DfoTcW
     x1caUYtfF44wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEANUxxgPqb
     QhmklL49o0z7VElXkLDO9kCy6hDEKhYT7VazC7J4MeMIDGXlWWlbOkOJvK6KwzU/
     78PsnRUc2XG1K6awXXtdjsaI2iQRuQYlOyZI0qO6FFefb7TWsr0DJBJTu97H0hMH
     A4O5bp0+ECy6WyAscY/qQBWGlzYRp9xPkTgQ72WAm9qAKQfloaSAQy3T+XIVUjvL
     c5yZhnn6ZZqjqoTjKFd549arei6LEqbUhLD7hTYvuLZPYlxFTLdAswHm+qcIGOe6
     Rv39QhPkkG0p4GlDkq+DMD62CnGHxn6e04NCp3PE4fNdUoFeS+uxhkTirS9/Pfd5
     wzQaDW079btvCg==
     -----END CERTIFICATE-----

   apibuilder4elastic.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDEjCCAfqgAwIBAgIIRG8XwqybPOIwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE
      AxMHZWxrZGVtbzAeFw0yMTAxMjkwNTEyMjBaFw0yNDAxMjkwNTEyMjBaMB0xGzAZ
      BgNVBAMTEmFwaWJ1aWxkZXI0ZWxhc3RpYzCCASIwDQYJKoZIhvcNAQEBBQADggEP
      ADCCAQoCggEBAMEIANRRPMWqsBtEoNx2j94szIoh6ewpd162tt01H5SMfmBwf1bH
      X22jbJ8QIgnI/fVBQ2RXsi4hY15YtALyUx1av4xyutN/5lqGecFE7jfEOH2bR7lk
      /oY3IRmuD/zXnOyFB1EREJB2fj0TBzXns6nAzKgZG4ZMQgmAWF1bLoB/cgPemBNk
      Y+5n10h/3jacq2xLKjpp8duMNobvLMuz9KV/0q8oEQWdXPGgMl1y7xMby2ieS4YX
      rxZVrKumCy0I4cmpgPVNKR8IownSLeLh3fSGfqVuaixjmjvN+HF+1Kwz6JVxrLhm
      skwpGhd6J5gzLDrKsnBs1+JK+4gISA2/ukkCAwEAAaNhMF8wHQYDVR0OBBYEFMhc
      TrHnEQ0NspJA4bp51vBesJsLMB0GA1UdEQQWMBSCEmFwaWJ1aWxkZXI0ZWxhc3Rp
      YzAfBgNVHSMEGDAWgBQnwa9Q3xJz4N+hNxbHVxpRi18XjjANBgkqhkiG9w0BAQsF
      AAOCAQEAk23MojHYZgonGE13N0k0M1WxS3hR32JEqScmJiIbBGulUtmNX3r56W1m
      BNbJVH/iGxYZYB5W+Ml3lzWpkeRouw9F0tBXstEA7p9QsMJF2IakYPQxlGDtX7eb
      iF4wtUo48jiUlYt6vTksoPGy02v2hsi/aqpeJ+YPi8y3kMA2vHltbags5RdDcxez
      uKQyVo0n7UmWFGxKc4AfV9SkMQnc598BX+vgLgnwlfUd9D+zGstn2HQc2HXjdXBG
      F8oXLuEiqSFmexs+/9m9qd2MRSXC7jfBoNqMzRYxIF3slh2ELc9dEuUEaLcLuD1/
      WLJOdnCGbka6pNtQ45dggm17gLzisg==
      -----END CERTIFICATE-----

{{- range $path, $config := .Values.logstash.logstashConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
