---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.logstash.name }}-headless"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.logstash.name | quote }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{- if .Values.logstash.labels }}
{{ toYaml .Values.logstash.labels | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.logstash.name | quote }}
  ports:
    - name: http
      port: {{ .Values.logstash.httpPort }}
