{{- if .Values.logstash.logstashPipeline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logstash.name }}-pipeline
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.logstash.name }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstash.logstashPipeline }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}
