#http.host: 0.0.0.0
network.host: 0.0.0.0

cluster.name: ${ELASTICSEARCH_CLUSTERNAME}

http.cors.allow-origin: "*"
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization. Access-Control-Allow-Headers, Accept

# Don't allow (e.g. Logstash) to auto-create indices that should be created by API-Builder
action.auto_create_index: "-apigw-*,+*"

bootstrap.memory_lock: true

# Enable security in general
xpack.security.enabled: true

# Initially provide anonymous access, which can be changed to user based AuthN.
#xpack.security.authc.anonymous.roles: kibana_admin,  superuser, beats_system, logstash_system
#xpack.security.authc.anonymous.username: anonymous

xpack.monitoring.collection.enabled: ${SELF_MONITORING_ENABLED:false}

# Don't enable this - This is just for testing!
#cluster.routing.allocation.disk.watermark.high: "94%"
#cluster.routing.allocation.disk.watermark.low: "93%"
