http.host: 0.0.0.0

http.cors.allow-origin: "*"
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization. Access-Control-Allow-Headers, Accept

node.name: elasticsearch1
discovery.type: single-node
bootstrap.memory_lock: true

# Enable security in general
xpack.security.enabled: true

xpack.security.authc.anonymous.roles: kibana_admin,  superuser, beats_system, logstash_system
xpack.security.authc.anonymous.username: anonymous

xpack.monitoring.collection.enabled: true