version: '3.7'
services:
  # Supposed to run side-by-side with the API-Gateway to watch the Open-Traffic Event files and send event to Logstash
  # You may also use a natively installed Filebeat (7.x) instance as long as it using the same configuration filebeat/filebeat.yml
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    # This custom entrypoint is required to adjust the variable LOGSTASH_HOSTS as it is required by Filebeat
    entrypoint: /usr/local/scripts/filbeat-custom-entrypoint.sh
    container_name: filebeat
    # Fixed Hostname as Filebeat is exposing the hostname instead of the configured name
    hostname: 'Filebeat ${GATEWAY_NAME:-"API-Gateway"}'
    command: --strict.perms=false
    environment:
      - LOGSTASH_HOSTS=${LOGSTASH_HOSTS}
      - LOGSTASH=${LOGSTASH} # Deprecated, will be removed in a future release
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_CLUSTER_UUID=${ELASTICSEARCH_CLUSTER_UUID}
      - ELASTICSEARCH_CRT=${ELASTICSEARCH_CRT}
      - BEATS_SYSTEM_USERNAME=${BEATS_SYSTEM_USERNAME}
      - BEATS_SYSTEM_PASSWORD=${BEATS_SYSTEM_PASSWORD}
      - GATEWAY_NAME=${GATEWAY_NAME}
      - GATEWAY_REGION=${GATEWAY_REGION}
      - FILEBEAT_WORKER=${FILEBEAT_WORKER}
      - SELF_MONITORING_ENABLED=${SELF_MONITORING_ENABLED}
    ports:
      - 5066:5066
    volumes:
      - type: volume
        source: filebeatdata
        target: /usr/share/filebeat/data # Required to make sure that Filebeat remembers the last position, even if the container is recreated
      - /etc/localtime:/etc/localtime:ro # Required to sync timezone of API-Gateway into the Filebeat Docker-Container
      - ${PWD}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${APIGATEWAY_OPENTRAFFIC_FOLDER}:/var/log/opentraffic
      - ${APIGATEWAY_TRACES_FOLDER}:/var/log/trace
      - ${APIGATEWAY_EVENTS_FOLDER}:/var/log/events
      - ${APIGATEWAY_AUDITLOGS_FOLDER}:/var/log/audit
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config/certificates:/usr/share/filebeat/config/certificates
      - ${PWD}/filebeat/scripts:/usr/local/scripts
    networks:
      - elastic
    logging:
      options:
        max-file: "3"
        max-size: "10m"

volumes:
  filebeatdata:

networks:
  elastic:
