# Please don't change this file as it is supposed to be overwritten as 
# part of fixes or enhancements.
#
# If you are missing a certain feature or discover a bug, please raise an issue instead:
# https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/issues
name: Filebeat ${GATEWAY_NAME:"API-Gateway"}
filebeat.inputs:
- type: log
  paths: ["/var/log/opentraffic/*.log"]
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  fields:
    logtype: openlog
    gatewayName: ${GATEWAY_NAME:"API-Gateway"}
    gatewayRegion: ${GATEWAY_REGION:"N/A"}
    filebeatVersion: "2"

- type: log
  paths: ["/var/log/trace/*.trc"]
  multiline.pattern: '^\[ALERT|TRACE|DEBUG|NOTICE|INFO|WARNING|ERROR|CRITICAL|FATAL|SEVERE]'
  multiline.negate: true
  # any line that does not match the above pattern belongs to the previous line
  multiline.match: after
  fields_under_root: true
  # The offset is used to sort the trace messages additionally to the timestamp
  offset: true
  fields:
    logtype: trace
    gatewayName: ${GATEWAY_NAME:"API-Gateway"}
    gatewayRegion: ${GATEWAY_REGION:"N/A"}
    filebeatVersion: "2"

- type: log
  paths: ["/var/log/events/*.log", "/var/log/events/processed/*.log.PROCESSED"]
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  fields:
    logtype: events
    gatewayName: ${GATEWAY_NAME:"API-Gateway"}
    gatewayRegion: ${GATEWAY_REGION:"N/A"}
    filebeatVersion: "2"

- type: log
  paths: ["/var/log/audit/*.log"]
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  fields:
    logtype: domainaudit
    gatewayName: ${GATEWAY_NAME:"API-Gateway"}
    gatewayRegion: ${GATEWAY_REGION:"N/A"}
    filebeatVersion: "2"

# Required for Trace-Messages logged by the API-Gateway
processors:
  - add_locale:  

output.logstash:
  hosts: ["${LOGSTASH}"]
  worker: ${FILEBEAT_WORKERS:2}

monitoring:
  enabled: true
  # Get the Cluster-ID (cluster_uuid) with this simple query: https://elasticsearch1:9200/
  # This links this filebeat instance to the Cluster with the given ID to enable monitoring
  # It's also required to setup the beats_system user
  cluster_uuid: ${ELASTICSEARCH_CLUSTER_UUID:ELASTICSEARCH_CLUSTER_UUID-NOT-SET}
  elasticsearch:
    hosts: ${ELASTICSEARCH_HOSTS}
    ssl.enabled: true
    ssl.certificate_authorities: ["${ELASTICSEARCH_CRT:ELASTICSEARCH_CRT-NOT-SET}"]
    username: "${BEATS_SYSTEM_USERNAME:beats_system}"
    password: "${BEATS_SYSTEM_PASSWORD:BEATS_SYSTEM_PASSWORD-NOT-SET}"