name: ${FILEBEAT_NAME:"Filebeat Gateway"}
filebeat.inputs:
- input_type: log
  paths: ["/var/log/opentraffic/*.log"]
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  fields:
    logtype: openlog

- input_type: log
  paths: ["/var/log/trace/*.trc"]
  multiline.pattern: '^\[ALERT|TRACE|DEBUG|NOTICE|INFO|WARNING|ERROR|CRITICAL|FATAL|SEVERE]'
  multiline.negate: true
  # any line that does not match the above pattern belongs to the previous line
  multiline.match: after
  fields_under_root: true
  fields:
    logtype: trace

- input_type: log
  paths: ["/var/log/events/*.log", "/var/log/events/processed/*.log.PROCESSED"]
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  fields:
    logtype: events

output.logstash:
  hosts: ["${LOGSTASH}"]

monitoring:
  enabled: true
  # Get the Cluster-ID (cluster_uuid) with this simple query: http://elasticsearch1:9200/
  # This links this filebeat instance to the Cluster with the given ID
  cluster_uuid: ${ELASTICSEARCH_CLUSTER_UUID}
  elasticsearch:
    hosts: ["${ELASTICSEARCH_HOST}"]
