triggers:
  kpis-index-kpis-manager:
    name: KPIs for Manager
    parameters:
      id: index-kpis-manager
    enabled: true
    invoke:
      flow: IndexSingleAPI-ManagerKPIs
      parameters:
        request: $.request
        config: $.config
        env: $.env
        organizationKPIs: 'false'
  kpis-get-manager-organization:
    name: Flow Listener
    parameters:
      id: get-manager-organization
    enabled: true
    invoke:
      flow: KPIs-IndexAPI-ManagerOrganizations(Sub-Flow)
      parameters:
        request: $.request
        config: $.config
        env: $.env
  kpis-index-kpis-organization:
    name: KPIs for Organization
    parameters:
      id: index-kpis-organization
    enabled: true
    invoke:
      flow: IndexSingleAPI-ManagerKPIs
      parameters:
        request: $.request
        config: $.config
        env: $.env
        organizationKPIs: 'true'
