# timer
triggers:
  setup-traffic-summary-index:
    enabled: true
    name: Setup Traffic-Summary Index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "traffic-summary"

  setup-traffic-details-index:
    enabled: true
    name: Setup Traffic-Details Index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "traffic-details"

  setup-traffic-trace-index:
    enabled: true
    name: Setup Traffic-Trace message index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "traffic-trace"

  setup-trace-messages-index:
    enabled: true
    name: Setup Trace-Messages Index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "trace-messages"

  setup-apigw-monitoring-index:
    enabled: true
    name: Setup API-GW Monitoring Index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "apigw-monitoring"

  setup-domainaudit-index:
    enabled: true
    name: Setup Domain-Audit Index
    parameters:
      interval: "10000"
    invoke:
      flow: SetupElasticsearchIndex
      parameters:
        config: $.config
        env: $.env
        indexName: "apigw-domainaudit"