apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.memcached.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    ncp/http-redirect: "true"
    kubernetes.io/ingress.class: "nsx"
spec:
  tls:
  - hosts:
    - {{ .Values.memcached.name }}.{{ .Values.global.domainName }}
    secretName: memcached-ingress-cert
  rules:
  - host: {{ .Values.memcached.name }}.{{ .Values.global.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.memcached.name }}
          servicePort: {{ .Values.memcached.trafficPort }}
