apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.memcached.name | quote }}
  name: {{ .Values.memcached.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  clusterIP: None
  ports:
  - name: {{ .Values.memcached.name }}
    port: {{ .Values.memcached.trafficPort }}
    targetPort: {{ .Values.memcached.trafficPort }}
    protocol: TCP
  selector:
    app: {{ .Values.memcached.name | quote }}
  sessionAffinity: ClientIP
  type: ClusterIP
