version: '3.7'
services:
  # This is optional, but good to have to perform manual queries and create custom dashboards
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    # This custom entrypoint is required to adjust the variable ELASTICSEARCH_HOSTS from Comma to Space separated
    entrypoint: /usr/share/kibana/scripts/kibana-custom-entrypoint.sh
    container_name: kibana
    environment:
      - SERVER_NAME=Kibana-Axway-APIM
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - KIBANA_SYSTEM_USERNAME=${KIBANA_SYSTEM_USERNAME}
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - KIBANA_SECURITY_ENABLED=${KIBANA_SECURITY_ENABLED:-false}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${ELASTICSEARCH_CA}
      - SERVER_SSL_ENABLED="true"
      - SERVER_SSL_KEY=${KIBANA_KEY}
      - SERVER_SSL_KEYPASSPHRASE=${KIBANA_KEYPASSPHRASE}
      - SERVER_SSL_CERTIFICATE=${KIBANA_CRT}
      - SELF_MONITORING_ENABLED=${SELF_MONITORING_ENABLED}
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - ${PWD}/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/config/certificates:/usr/share/kibana/config/certificates
      - ${PWD}/kibana/scripts:/usr/share/kibana/scripts
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    networks:
      - elastic
      - ingress
    logging:
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  esdata1:
  logs:

networks:
  elastic:
  ingress:
