{{- if .Values.global.generateCertificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "certificates.fullname" . }}
  labels:
    app: "{{ template "certificates.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "elastic-apim.gen-certs" . ) | indent 2 }}
{{- end }}