logging.level: info

setup.dashboards:
  enabled: ${METRICBEAT_SETUP_DASHBOARDS:true}
  directory: activeDashboards

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: system
  period: 10s
  hostsfs: true
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    #- entropy
    #- core
    - diskio
    #- socket
    #- service
    #- users
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${METRICBEAT_USERNAME}'
  password: '${METRICBEAT_PASSWORD}'
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]

setup.kibana:
  host: "${KIBANA_HOST}"
  username: "${METRICBEAT_USERNAME}"
  password: "${METRICBEAT_PASSWORD}"
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]