apibuilder4elastic:
  secrets:
    elasticsearchUsername: "elastic"
    elasticsearchPassword: "TGSOaIKtajLtAEdPupSS"

elasticsearch:
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "500m"
  replicas: 2

logstash:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "1536Mi"
    limits:
      cpu: "1000m"
      memory: "1536Mi"
  logstashSecrets:
    logstashSystemUsername: "logstash_system"
    logstashSystemPassword: "sXGdK8PHYeaX4CKBtB93"

kibana:
  kibanaSecrets:
    username: "kibana_system"
    password: "0uOtilmJEIdMHyljdqvd"