{{- if and .Values.logstash.enabled .Values.elasticsearch.ssl.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logstash.fullname" . }}-secret
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
type: Opaque
data:
  xpack.security.http.ssl.key_passphrase: {{ default "" .Values.elasticsearch.ssl.password | b64enc | quote }}
{{- end }}