{{- if and .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.fullname" . }}-secret
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
type: Opaque
data:
  xpack.security.http.ssl.key_passphrase: {{ default "" .Values.elasticsearch.ssl.password | b64enc | quote }}
  {{- if .Values.elasticsearch.elasticsearchSecrets.enabled }}
  ELASTIC_USERNAME: {{ default "" .Values.elasticsearch.elasticsearchSecrets.elasticUsername | b64enc | quote }}
  ELASTIC_PASSWORD: {{ default "" .Values.elasticsearch.elasticsearchSecrets.elasticPassword | b64enc | quote }}
  {{- end }}
{{- end }}