{{- if and ".Values.apm-server.enabled" ".Values.apm-server.apmserverSecrets.enabled" }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apmserver.fullname" . }}-secret
  labels:
    {{- include "apmserver.labels" . | nindent 4 }}
type: Opaque
data:
  APM_USERNAME: {{ index .Values "apm-server" "apmserverSecrets" "username" | b64enc | quote }}
  APM_PASSWORD: {{ index .Values "apm-server" "apmserverSecrets" "password" | b64enc | quote }}
{{- end }}