{{- if and .Values.kibana.enabled .Values.kibana.kibanaSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana.fullname" . }}-secret
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
  KIBANA_SYSTEM_USERNAME: {{ default "" .Values.kibana.kibanaSecrets.username | b64enc | quote }}
  KIBANA_SYSTEM_PASSWORD: {{ default "" .Values.kibana.kibanaSecrets.password | b64enc | quote }}
{{- end }}