logging.level: info

setup.dashboards:
  enabled: ${METRICBEAT_SETUP_DASHBOARDS:true}
  directory: activeDashboards

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  enabled: ${METRICBEAT_DOCKER_ENABLED}
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s
  enabled: true

- module: logstash
  enabled: ${METRICBEAT_LOGSTASH_ENABLED}
  xpack.enabled: true
  period: 30s
  hosts: ["logstash:9600"]
  #username: "user"
  #password: "secret"

- module: memcached
  enabled: ${METRICBEAT_MEMCACHED_ENABLED}
#  metricsets: ["stats"]
  period: 30s
  hosts: ["memcached:11211"]

- module: beat
  enabled: ${METRICBEAT_BEAT_ENABLED}
  xpack.enabled: true
  period: 30s
  hosts: ["http://filebeat:5066"]

- module: elasticsearch
  enabled: ${METRICBEAT_ELASTICSEARCH_ENABLED}
  xpack.enabled: true
  period: 30s
  hosts: ${ELASTICSEARCH_HOSTS}
  username: '${METRICBEAT_USERNAME:""}'
  password: '${METRICBEAT_PASSWORD:""}'
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]

- module: kibana
  enabled: ${METRICBEAT_KIBANA_ENABLED}
  xpack.enabled: true
  period: 30s
  hosts: ["${KIBANA_HOST}"]
  username: '${METRICBEAT_USERNAME:""}'
  password: '${METRICBEAT_PASSWORD:""}'
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]

- module: system
  enabled: ${METRICBEAT_SYSTEM_ENABLED}
  period: 30s
  hostsfs: true
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    #- entropy
    #- core
    - diskio
    #- socket
    #- service
    #- users
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  enabled: ${METRICBEAT_SYSTEM_ENABLED}
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'

- module: system
  enabled: ${METRICBEAT_SYSTEM_ENABLED}
  period: 15m
  metricsets:
    - uptime

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${METRICBEAT_USERNAME:""}'
  password: '${METRICBEAT_PASSWORD:""}'
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]

setup.kibana:
  host: "${KIBANA_HOST}"
  username: '${METRICBEAT_USERNAME:""}'
  password: '${METRICBEAT_PASSWORD:""}'
  ssl.enabled: true
  ssl.certificate_authorities: ["${ELASTICSEARCH_CA:ELASTICSEARCH_CA-NOT-SET}"]