apiVersion: v1
kind: ConfigMap
metadata:
  name: apibuilder4elastic-debug
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apibuilder4elastic.name }}
data:
  debug.sh: |
    #!/bin/sh -e
    # This script is to debug

    ls -l /app
    ls -l /app/certificates
    ls -l /app/config

