{{- if .Values.apibuilder4elastic.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apibuilder4elastic.fullname" . }}-config
  labels:
    {{- include "apibuilder4elastic.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_HOSTS: {{ required "The value global.elasticsearchHosts is missing." .Values.global.elasticsearchHosts | quote }}
  ELASTICSEARCH_CA: {{ required "The path to the CA for API-Builder to Elasticsearch communication is missing" .Values.global.elasticsearchCa | quote }}
  ELASTICSEARCH_SSL_VERIFICATIONMODE: {{ default true .Values.apibuilder4elastic.validateElasticsearchCertificate | quote }}
  ADMIN_NODE_MANAGER: {{ required "The Admin-Node-Manager URL (apibuilder4elastic.anmUrl) is required." .Values.apibuilder4elastic.anmUrl | quote }}
  API_MANAGER: {{ default "" .Values.apibuilder4elastic.apimgrUrl | quote }}
  API_BUILDER_SSL_CERT: {{ default "config/certificates/apibuilder4elastic.crt" .Values.apibuilder4elastic.ssl.cert | quote }}
  API_BUILDER_SSL_KEY: {{ default "config/certificates/apibuilder4elastic.key" .Values.apibuilder4elastic.ssl.key | quote }}
  API_BUILDER_LOCAL_API_LOOKUP_FILE: {{ default "" .Values.apibuilder4elastic.localAPILookup | quote}}
  AUTHZ_CONFIG: {{ default "" .Values.apibuilder4elastic.authzConfig | quote}}
  PAYLOAD_HANDLING_ENABLED: {{ default true .Values.apibuilder4elastic.payloadEnabled | quote }}
  MANAGEMENT_KPIS_ENABLED: {{ default true .Values.apibuilder4elastic.managementKPIsEnabled | quote }}
  LOG_LEVEL: {{ default "info" .Values.apibuilder4elastic.logLevel | quote }}
  APM_ENABLED: {{ index .Values "apm-server" "enabled" | quote }}
{{- if .Values.apibuilder4elastic.apmserver.serverUrl }}
  APM_SERVER: {{ .Values.apibuilder4elastic.apmserver.serverUrl | quote }}
{{- else }}
  APM_SERVER: {{ printf "https://%s-apm-server:8200" .Release.Name | quote }}
{{- end }}  
  APM_VALIDATE_SERVER_CERT: {{ default true .Values.apibuilder4elastic.apmserver.verifyServerCert | quote }}
  APM_SERVER_CA: {{ default "" .Values.apibuilder4elastic.apmserver.serverCaCertFile | quote }}
{{- end }}