{{- if and .Values.apibuilder4elastic.enabled .Values.apibuilder4elastic.ingress.enabled -}}
{{- $fullName := include "apibuilder4elastic.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "apibuilder4elastic.fullname" . }}-ingress
  labels:
    {{- include "apibuilder4elastic.labels" . | nindent 4 }}
{{- with .Values.apibuilder4elastic.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.apibuilder4elastic.ingress.tls }}
  tls:
{{ toYaml .Values.apibuilder4elastic.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range $.Values.apibuilder4elastic.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort }}
        {{- end }}
  {{- end }}
{{- end }}