{{- if .Values.apibuilder4elastic.enabled }}
{{- if or .Values.apibuilder4elastic.secrets .Values.apibuilder4elastic.ssl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apibuilder4elastic.fullname" . }}-secret
  labels:
    {{- include "apibuilder4elastic.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.apibuilder4elastic.secrets }}
  {{- if .Values.apibuilder4elastic.secrets.apimgrUsername }}
  API_MANAGER_USERNAME: {{ .Values.apibuilder4elastic.secrets.apimgrUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.apibuilder4elastic.secrets.apimgrPassword }}
  API_MANAGER_PASSWORD: {{ .Values.apibuilder4elastic.secrets.apimgrPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.apibuilder4elastic.secrets.elasticsearchUsername }}
  API_BUILDER_USERNAME: {{ .Values.apibuilder4elastic.secrets.elasticsearchUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.apibuilder4elastic.secrets.elasticsearchPassword }}
  API_BUILDER_PASSWORD: {{ .Values.apibuilder4elastic.secrets.elasticsearchPassword | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.apibuilder4elastic.ssl }}
  {{- if .Values.apibuilder4elastic.ssl.password }}
  API_BUILDER_SSL_KEY_PASSWORD: {{ .Values.apibuilder4elastic.ssl.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}