apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    apigw.version: {{ .Values.global.apimVersion | quote }}
    apigw.editor: {{ .Values.global.editor | quote }}
  labels:
    app: {{ .Values.apibuilder4elastic.name }}
  name: {{ .Values.apibuilder4elastic.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.apibuilder4elastic.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apibuilder4elastic.name | quote }}
  strategy:
    type: {{ .Values.global.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ .Values.apibuilder4elastic.name | quote }}
    spec:
      containers:
      - env:
        - name: TZ
          value: "{{ .Values.global.timeZone }}"
        - name: ELASTICSEARCH_HOSTS
          value: {{ .Values.global.elasticsearch.url }}
        - name: ADMIN_NODE_MANAGER
          value: {{ .Values.apibuilder4elastic.anm.url }}
        - name: API_MANAGER
          value: {{ .Values.apibuilder4elastic.apimgr.url }}
        - name: API_MANAGER_USERNAME
          value: {{ .Values.apibuilder4elastic.apimgr.adminUser }}
        - name: API_MANAGER_PASSWORD
          value: {{ .Values.apibuilder4elastic.apimgr.adminPasswd }}
        - name: API_BUILDER_USERNAME
          value: {{ .Values.apibuilder4elastic.userName }}
        - name: API_BUILDER_PASSWORD
          value: {{ .Values.apibuilder4elastic.userPasswd }}
        - name: API_BUILDER_SSL_CERT
          value: {{ .Values.apibuilder4elastic.ssl.cert }}
        - name: API_BUILDER_SSL_KEY
          value: {{ .Values.apibuilder4elastic.ssl.key }}
        - name: API_BUILDER_SSL_KEY_PASSWORD
          value: {{ .Values.apibuilder4elastic.ssl.keyPasswd }}
        - name: API_BUILDER_LOCAL_API_LOOKUP_FILE
          value: {{ .Values.apibuilder4elastic.localAPILookup | quote}}
        - name: AUTHZ_CONFIG
          value: {{ .Values.apibuilder4elastic.authzConfig | quote}}
        - name: SKIP_PAYLOAD_HANDLING
          value: {{ .Values.apibuilder4elastic.skipPayload | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.apibuilder4elastic.logLevel }}
        image: {{ .Values.apibuilder4elastic.imageName }}:{{ .Values.apibuilder4elastic.buildTag }}
        imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
        name: {{ .Values.apibuilder4elastic.name }}
        volumeMounts:
        - name: apib-cert
          mountPath: /app/config
        - name: apib-payload
          mountPath: /var/log/payloads
        - name: apibuilder4elastic-debug
          mountPath: /app/debug.sh
          subPath: debug.sh
        ports:
        - containerPort: {{ .Values.apibuilder4elastic.trafficPort }}
        resources:
          limits:
            memory: {{ .Values.apibuilder4elastic.memoryLimits | quote }}
            cpu: {{ .Values.apibuilder4elastic.cpuLimits | quote }}
          requests:
            memory: {{ .Values.apibuilder4elastic.memoryRequests | quote }}
            cpu: {{ .Values.apibuilder4elastic.cpuRequests | quote }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.apibuilder4elastic.trafficPort }}
          initialDelaySeconds: 40
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: {{ .Values.apibuilder4elastic.trafficPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["sleep","90"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        #command:
        #- /app/debug.sh
      restartPolicy: Always
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      volumes:
        - name: apib-payload
          hostPath:
            path: {{ .Values.global.hostPath.base }}/apimgr/logs/payload
            type: DirectoryOrCreate
        - name: apib-cert
          secret:
            secretName: apibuilder4elastic-secret
        - name: apibuilder4elastic-debug
          configMap:
            name: apibuilder4elastic-debug
            defaultMode: 0755
status: {}
