apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.apibuilder4elastic.name }}
  name: {{ .Values.apibuilder4elastic.name }}-secret
  namespace: {{ .Values.global.namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: |
     MIIDEjCCAfqgAwIBAgIIRG8XwqybPOIwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE
     AxMHZWxrZGVtbzAeFw0yMTAxMjkwNTEyMjBaFw0yNDAxMjkwNTEyMjBaMB0xGzAZ
     BgNVBAMTEmFwaWJ1aWxkZXI0ZWxhc3RpYzCCASIwDQYJKoZIhvcNAQEBBQADggEP
     ADCCAQoCggEBAMEIANRRPMWqsBtEoNx2j94szIoh6ewpd162tt01H5SMfmBwf1bH
     X22jbJ8QIgnI/fVBQ2RXsi4hY15YtALyUx1av4xyutN/5lqGecFE7jfEOH2bR7lk
     /oY3IRmuD/zXnOyFB1EREJB2fj0TBzXns6nAzKgZG4ZMQgmAWF1bLoB/cgPemBNk
     Y+5n10h/3jacq2xLKjpp8duMNobvLMuz9KV/0q8oEQWdXPGgMl1y7xMby2ieS4YX
     rxZVrKumCy0I4cmpgPVNKR8IownSLeLh3fSGfqVuaixjmjvN+HF+1Kwz6JVxrLhm
     skwpGhd6J5gzLDrKsnBs1+JK+4gISA2/ukkCAwEAAaNhMF8wHQYDVR0OBBYEFMhc
     TrHnEQ0NspJA4bp51vBesJsLMB0GA1UdEQQWMBSCEmFwaWJ1aWxkZXI0ZWxhc3Rp
     YzAfBgNVHSMEGDAWgBQnwa9Q3xJz4N+hNxbHVxpRi18XjjANBgkqhkiG9w0BAQsF
     AAOCAQEAk23MojHYZgonGE13N0k0M1WxS3hR32JEqScmJiIbBGulUtmNX3r56W1m
     BNbJVH/iGxYZYB5W+Ml3lzWpkeRouw9F0tBXstEA7p9QsMJF2IakYPQxlGDtX7eb
     iF4wtUo48jiUlYt6vTksoPGy02v2hsi/aqpeJ+YPi8y3kMA2vHltbags5RdDcxez
     uKQyVo0n7UmWFGxKc4AfV9SkMQnc598BX+vgLgnwlfUd9D+zGstn2HQc2HXjdXBG
     F8oXLuEiqSFmexs+/9m9qd2MRSXC7jfBoNqMzRYxIF3slh2ELc9dEuUEaLcLuD1/
     WLJOdnCGbka6pNtQ45dggm17gLzisg==
  tls.key: |
     MIIEowIBAAKCAQEAwQgA1FE8xaqwG0Sg3HaP3izMiiHp7Cl3Xra23TUflIx+YHB/
     VsdfbaNsnxAiCcj99UFDZFeyLiFjXli0AvJTHVq/jHK603/mWoZ5wUTuN8Q4fZtH
     uWT+hjchGa4P/Nec7IUHUREQkHZ+PRMHNeezqcDMqBkbhkxCCYBYXVsugH9yA96Y
     E2Rj7mfXSH/eNpyrbEsqOmnx24w2hu8sy7P0pX/SrygRBZ1c8aAyXXLvExvLaJ5L
     hhevFlWsq6YLLQjhyamA9U0pHwijCdIt4uHd9IZ+pW5qLGOaO834cX7UrDPolXGs
     uGayTCkaF3onmDMsOsqycGzX4kr7iAhIDb+6SQIDAQABAoIBAQC4WGhSW/Lp44Sj
     xfrKEQB8cdQ05wZ7X258qYoh36X1O+dFOqqhuW3NSxFlJwcayTSfkGBH5+hmXcSE
     SbpARiRSGGRuQPNjIPZg5aRJiwblgyNf8Xeh+m2IyAV4fN8P3OokhzbhmKZ1EHSm
     5xEvzcOrDlFlB/VdYF6ArG23WmkilOlaDPHD+pi3TIt51wecncgjcJvrWA1UKaGN
     w0YuBYvAe56hHMXahPNWilDzEbiKFpZ9nbFGoyni+fpkApxyITNANguXXqpuXaeh
     q3tKsheegQn1+PoDljfCkqZUOB9pPzlm0n+1c2I18ryzEupqOKbwReNHewpMUENU
     iUn7cSfxAoGBAPQvCQLVwXqgmEL9DIMNmPWMEthyPuklNnDE2RSyeO0bihmz3xpK
     VWta9mUG/oGmztk9UmlUf6VRxn+AEANU3wKTIHGy3u7sIdvX439i+wP/6dFN859R
     EFdg2yEhbahyebJefa3JP5UJZZ4kExdBugPn4GL7pvaQ5R0adaJ0IU2zAoGBAMpf
     Saot1IgDj0TzXon8mupXKUDuKIteufGTRjITEEmQPrqU+3uFIZHUc66fXVwt63cJ
     Ikxsksi9lw6M/sFbu1C0CPhuHxktndUvuizlQJTxSb3SPYVJoUGsji9KUHmO5Ew2
     N58oRcrgvb88bFNyIIqy1hLdq4PupicNEsaQfjITAoGAL3IMMC7Ufz1BGJMOoVA9
     Dkj/SGs6aha+8z5sZ6cd9ARL2x6mFPeojUmJYqvvO8Xrny5ZGvo+KyMujIuXkO4m
     vttTjIQS6R2cnpjeLVxQJcDN78tTsPsRT8kUCuXx5q8Hkm7lwKS/4/eFdSrRQs2U
     lTmy0cjP8kzJF9SSUtR5vB0CgYAebzYk4b+UtPRW6kLNfa/Ojk0l9qsiSpysN/nW
     jgdlCMxmQwGPEfZ6d/jtygnAUyeWP0lpNOreRaTyC0JE0gbZnDm9ItKKdtHFvefB
     2LhdrevpIDUgVnJp7gl0EzkHDvZGf+DdjrDwUdw3Zl7kLcW3Fi4bqDqjHMDgHpc0
     RYa1AQKBgAGHvxCPOOam6FXo+mGaq/9/DvvF1kr2oQk4kfZPWKz0oPLLnaCUqeDQ
     0L0V5FU97i9UopFdUH2rneI2Zo5mN6dQoX5WCjDCKNs5B/yiqPGitxNOEzah6hCA
     soN2vKih+xWssf8/DVjWvdBRXONu6eFpup31I5vflbBhsbuPwjuE
