name: Bug report
description: Create a report to help us to improve the solution
labels: [bug]
assignees:
  - cwiechmann
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: elkSolutionVersion
    attributes:
      label: ELK-Solution version
      description: "The ELK-Solution version you are using"
      placeholder: "4.1.0"
    validations:
      required: true
  - type: input
    id: elasticstackVersion
    attributes:
      label: Elastic-Stack version
      description: "The version of your Elastic-Stack"
      placeholder: "7.17.0"
    validations:
      required: true
  - type: input
    id: apimanagementVersion
    attributes:
      label: API-Management version
      description: "The API-Management version you are using"
      placeholder: "7.7.0.20220228"
    validations:
      required: true  
  - type: input
    id: numberOfAPIs
    attributes:
      label: Number of APIs
      description: "Please provide the ap. number of APIs (not operations) you have in our API-Manager."
      placeholder: "55"
    validations:
      required: true
  - type: input
    id: numberOfApplications
    attributes:
      label: Number of Applications
      description: "Please provide the ap. number of applications"
      placeholder: "80"
    validations:
      required: true
  - type: input
    id: numberOfTransactions
    attributes:
      label: Number of Transactions
      description: "Please let us know the ap. maximum number of transactions for a period of 5 to 10 minutes on a typical day."
      placeholder: "150.000 transactions in 10 minutes"
    validations:
      required: true
  - type: dropdown
    id: elkDeploymentOptions
    attributes:
      label: API-Management deployment option
      description: How is the API-Management platfor deployed?
      options:
        - Classic VMs
        - Kubernetes plain
        - OpenShift
        - AWS EKS
        - Azure AKS
        - GCP GKE
        - Something else (please specify in the description!)
  - type: dropdown
    id: elkDeploymentOptions
    attributes:
      label: ELK-Solution deployment option
      description: Is the project deployed based on Docker-Compose or Container-Platform using HELM?
      options:
        - Classic VMs using Docker-Compose
        - Kubernetes plain
        - OpenShift
        - AWS EKS
        - Azure AKS
        - GCP GKE
        - Something else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell