version: '3.7'
services:
  # Elasticsearch node 1
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    # Custom entrypoint to configured ES based on given ELASTICSEARCH_HOSTS
    entrypoint: /usr/share/elasticsearch/scripts/custom-entrypoint.sh
    container_name: elasticsearch1
    environment:
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - cluster.name=${ELASTICSEARCH_CLUSTERNAME}
      - node.name=Elasticsearch1 # Don't change the format (name and number) as it is used to bootstrap the cluster and identify the node number
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_ANONYMOUS_ENABLED=${ELASTICSEARCH_ANONYMOUS_ENABLED:-true}
      - SELF_MONITORING_ENABLED=${SELF_MONITORING_ENABLED}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/${ELASTICSEARCH_KEY}
      - xpack.security.http.ssl.key_passphrase=${ELASTICSEARCH_KEY_PASSPHRASE}
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/${ELASTICSEARCH_CRT}
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/${ELASTICSEARCH_CA}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/${ELASTICSEARCH_KEY}
      - xpack.security.transport.ssl.key_passphrase=${ELASTICSEARCH_KEY_PASSPHRASE}
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/${ELASTICSEARCH_CRT}
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/${ELASTICSEARCH_CA}
      # Activate the following parameters for advanced setup
      #- network.publish_host=${ELASTICSEARCH_PUBLISH_HOST1}
      #- http.port=${ELASTICSEARCH_HOST1_HTTP}
      #- transport.port=${ELASTICSEARCH_HOST1_TRANSPORT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - ALL
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata1
        target: /usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${PWD}/config/certificates:/usr/share/elasticsearch/config/certificates
      - ${PWD}/elasticsearch/scripts:/usr/share/elasticsearch/scripts
    networks:
      - elastic
    ports:
      - ${ELASTICSEARCH_HOST1_HTTP:-9200}:${ELASTICSEARCH_HOST1_HTTP:-9200}
      - ${ELASTICSEARCH_HOST1_TRANSPORT:-9300}:${ELASTICSEARCH_HOST1_TRANSPORT:-9300}
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  # Metricbeat monitoring Elasticsearch node 1
  metricbeatES:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION}
    restart: on-failure:10
    entrypoint: /usr/local/scripts/metricbeat-entrypoint.sh
    container_name: metricbeatES1
    hostname: Elasticsearch1
    command: --strict.perms=false -e -c configs/metricbeat.elasticsearch-kibana.yml
    user: root # Required to monitor docker containers
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - KIBANA_HOST=${KIBANA_HOST}
      - ELASTICSEARCH_CLUSTER_UUID=${ELASTICSEARCH_CLUSTER_UUID}
      - ELASTICSEARCH_CA=${ELASTICSEARCH_CA}
      - METRICBEAT_USERNAME=${METRICBEAT_USERNAME}
      - METRICBEAT_PASSWORD=${METRICBEAT_PASSWORD}
      - METRICBEAT_ENABLED=${METRICBEAT_ENABLED}
      - METRICBEAT_SETUP_DASHBOARDS=${METRICBEAT_SETUP_DASHBOARDS}
      - ELASTICSEARCH_ANONYMOUS_ENABLED=${ELASTICSEARCH_ANONYMOUS_ENABLED}
    volumes:
      - type: volume
        source: metricbeatdata
        target: /usr/share/metricbeat/data 
      - /etc/localtime:/etc/localtime:ro # Required to sync timezone of the server into the Filebeat Docker-Container
      - ${PWD}/metricbeat/configs:/usr/share/metricbeat/configs
      - ${PWD}/metricbeat/activeDashboards:/usr/share/metricbeat/activeDashboards
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config/certificates:/usr/share/metricbeat/config/certificates
      - ${PWD}/metricbeat/scripts:/usr/local/scripts
    networks:
      - elastic
    logging:
      options:
        max-file: "3"
        max-size: "10m"

volumes:
  esdata1:
  logs:
  metricbeatdata:

networks:
  elastic: