version: '3.7'
services:
  # Elasticsearch node 4
  elasticsearch4:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    # Custom entrypoint to configured ES based on given ELASTICSEARCH_HOSTS
    entrypoint: /usr/share/elasticsearch/scripts/elasticsearch-custom-entrypoint.sh
    container_name: elasticsearch4
    environment:
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - cluster.name=${ELASTICSEARCH_CLUSTERNAME}
      - node.name=Elasticsearch4 # Don't change the format (name and number) as it is used to bootstrap the cluster and identify the node number
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_ANONYMOUS_ENABLED=${ELASTICSEARCH_ANONYMOUS_ENABLED:-true}
      - SELF_MONITORING_ENABLED=${SELF_MONITORING_ENABLED}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/${ELASTICSEARCH_KEY}
      - xpack.security.http.ssl.key_passphrase=${ELASTICSEARCH_KEY_PASSPHRASE}
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/${ELASTICSEARCH_CRT}
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/${ELASTICSEARCH_CA}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/${ELASTICSEARCH_KEY}
      - xpack.security.transport.ssl.key_passphrase=${ELASTICSEARCH_KEY_PASSPHRASE}
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/${ELASTICSEARCH_CRT}
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/${ELASTICSEARCH_CA}
      # Activate the following parameters for advanced setup
      #- network.publish_host=${ELASTICSEARCH_PUBLISH_HOST4}
      #- http.port=${ELASTICSEARCH_HOST4_HTTP}
      #- transport.port=${ELASTICSEARCH_HOST4_TRANSPORT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - ALL
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata4
        target: /usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${PWD}/config/certificates:/usr/share/elasticsearch/config/certificates
      - ${PWD}/elasticsearch/scripts:/usr/share/elasticsearch/scripts
    networks:
      - elastic
    ports:
      - ${ELASTICSEARCH_HOST1_HTTP:-9203}:${ELASTICSEARCH_HOST1_HTTP:-9203}
      - ${ELASTICSEARCH_HOST1_TRANSPORT:-9303}:${ELASTICSEARCH_HOST1_TRANSPORT:-9303}
    logging:
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  esdata4:
  logs:

networks:
  elastic: