{{- if and (eq .Values.filebeat.enabled true .Values.filebeat.filebeatSecrets.enabled true) | or .Values.filebeat.createFilebeatConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "filebeat.fullname" . }}-secret
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.filebeat.filebeatSecrets.beatsSystemUsername }}
  BEATS_SYSTEM_USERNAME: {{ .Values.filebeat.filebeatSecrets.beatsSystemUsername | b64enc | quote }}
  {{- else }}
  BEATS_SYSTEM_USERNAME: ""
  {{- end }}
  {{- if .Values.filebeat.filebeatSecrets.beatsSystemPassword }}
  BEATS_SYSTEM_PASSWORD: {{ .Values.filebeat.filebeatSecrets.beatsSystemPassword | b64enc | quote }}
  {{- else }}
  BEATS_SYSTEM_PASSWORD: ""
  {{- end }}
{{- end }}