# Disable security by default to fallback to anonymous user
# Enable this parameter to activate security for Kibana
xpack.security.enabled: false

server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "https://elasticsearch1:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "${KIBANA_USERNAME}"
elasticsearch.password: "${KIBANA_PASSWORD}"

xpack.encryptedSavedObjects.encryptionKey: "YT8d68CZE4Z3mXBxYDVqjC4hhts4H9TQ"