# Disable security by default to fallback to anonymous user
# Enable this parameter to activate security for Kibana
#xpack.security.enabled: true

# Should be disabled, when Kibana is monitored by Metricbeat
# No longer hard coded is handled by the entry-script
# monitoring.kibana.collection.enabled: true

server.name: kibana
elasticsearch.hosts: ${ELASTICSEARCH_HOSTS}
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "${KIBANA_SYSTEM_USERNAME}"
elasticsearch.password: "${KIBANA_SYSTEM_PASSWORD}"

xpack.encryptedSavedObjects.encryptionKey: "YT8d68CZE4Z3mXBxYDVqjC4hhts4H9TQ"
xpack.reporting.encryptionKey: "YT8d68CZE4Z3mXBxYDVqjC4hhts4H9TQ"
xpack.security.encryptionKey: "YT8d68CZE4Z3mXBxYDVqjC4hhts4H9TQ"

#xpack.reporting.kibanaServer.hostname: 0.0.0.0

monitoring.cluster_alerts.email_notifications.email_address: noreply@notification.email