apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    apigw.version: {{ .Values.global.apimVersion | quote }}
    apigw.editor: {{ .Values.global.editor | quote }}
  labels:
    app: {{ .Values.filebeat.name }}
  name: {{ .Values.filebeat.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.filebeat.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.filebeat.name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.filebeat.name | quote }}
    spec:
      containers:
      - args:
        - --strict.perms=false
        command:
        - /usr/local/scripts/filebeat-custom-entrypoint.sh
        env:
        #- name: BEATS_SYSTEM_USERNAME
        #  value: {{ .Values.filebeat.userName }}
        #- name: BEATS_SYSTEM_PASSWORD
        #  value: {{ .Values.filebeat.userPasswd }}
        - name: LOGSTASH_HOSTS
          value: {{ .Values.global.logstash.hosts }}
        #- name: ELASTICSEARCH_CLUSTER_UUID
        #  value: {{ .Values.global.elasticsearch.clusterUUID }}
        #- name: ELASTICSEARCH_HOSTS
        #  value: {{ .Values.global.elasticsearch.hosts }}
        #- name: ELASTICSEARCH_CRT
        #  value: {{ .Values.global.elasticsearch.cert }}
        #- name: FILEBEAT_WORKER
        #  value: {{ .Values.filebeat.worker }}
        #- name: GATEWAY_NAME
        #  value: {{ .Values.filebeat.apigw.name }}
        #- name: GATEWAY_REGION
        #  value: {{ .Values.filebeat.apigw.region }}
        - name: SELF_MONITORING_ENABLED
          value: {{ .Values.filebeat.selfMonitoring | quote }}
        image: {{ .Values.filebeat.imageName }}:{{ .Values.filebeat.buildTag }}
        imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
        name: {{ .Values.filebeat.name }}
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: filebeat-custom-entrypoint
          mountPath: /usr/local/scripts
        - name: filebeat-data
          mountPath: /usr/share/filebeat/data
        - name: filebeat-opentraffic
          mountPath: /var/log/opentraffic
        - name: filebeat-trace
          mountPath: /var/log/trace
        - name: filebeat-events
          mountPath: /var/log/events
        - name: filebeat-audit
          mountPath: /var/log/audit
        - name: filebeat-certs
          mountPath: /usr/share/filebeat/config/certificates
        ports:
        - containerPort: {{ .Values.filebeat.trafficPort }}
        resources:
          limits:
            memory: {{ .Values.filebeat.memoryLimits | quote }}
            cpu: {{ .Values.filebeat.cpuLimits | quote }}
          requests:
            memory: {{ .Values.filebeat.memoryRequests | quote }}
            cpu: {{ .Values.filebeat.cpuRequests | quote }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.filebeat.trafficPort }}
          initialDelaySeconds: 40
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: {{ .Values.filebeat.trafficPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["sleep","90"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      hostname: filebeat
      restartPolicy: Always
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
            defaultMode: 0755
        - name: filebeat-custom-entrypoint
          configMap:
            name: filebeat-custom-entrypoint
            defaultMode: 0755
        - name: filebeat-data
          hostPath:
            path: {{ .Values.global.hostPath.base }}/elkdemo/filebeat/data
            type: DirectoryOrCreate
        - name: filebeat-opentraffic
          hostPath:
            path: {{ .Values.global.hostPath.base }}/apimgr/logs/opentraffic
            type: DirectoryOrCreate
        - name: filebeat-trace
          hostPath:
            path: {{ .Values.global.hostPath.base }}/apimgr/trace
            type: DirectoryOrCreate
        - name: filebeat-events
          hostPath:
            path: {{ .Values.global.hostPath.base }}/anm/events
            type: DirectoryOrCreate
        - name: filebeat-audit
          hostPath:
            path: {{ .Values.global.hostPath.base }}/apimgr/logs
            type: DirectoryOrCreate
        - name: filebeat-certs
          hostPath:
            path: {{ .Values.global.hostPath.base }}/elkdemo/config/certificates
            type: DirectoryOrCreate
status: {}