apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.filebeat.name | quote }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    ncp/http-redirect: "true"
    kubernetes.io/ingress.class: "nsx"
spec:
  tls:
  - hosts:
    - {{ .Values.filebeat.name }}.{{ .Values.global.domainName }}
    secretName: filebeat-ingress-cert
  rules:
  - host: {{ .Values.filebeat.name }}.{{ .Values.global.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.filebeat.name }}
          servicePort: {{ .Values.filebeat.trafficPort }}
