# Please don't change this file as it is supposed to be overwritten as 
# part of fixes or enhancements.
#
# If you are missing a certain feature or discover a bug, please raise an issue instead:
# https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/issues

- pipeline.id: BeatsInput
  path.config: "pipelines/BeatsInputPipeline.conf"
  pipeline.workers: 4
  pipeline.ordered: false

- pipeline.id: OpenTraffic
  path.config: "pipelines/OpenTrafficPipeline.conf"
  pipeline.workers: 4
  pipeline.batch.size: 2000
  pipeline.ordered: false

- pipeline.id: TraceMessages
  path.config: "pipelines/TraceMessagesPipeline.conf"
  pipeline.workers: 1
  pipeline.ordered: true

- pipeline.id: Events
  path.config: "pipelines/EventsPipeline.conf"
  pipeline.workers: 1
  pipeline.ordered: false

- pipeline.id: DomainAudit
  path.config: "pipelines/DomainAuditPipeline.conf"
  pipeline.workers: 1
  pipeline.ordered: false