{{- if .Values.logstash.enabled }}
{{- $pipelinesYaml := .Files.Get "configuration/logstash/config/pipelines.yml" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-config
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data: 
  pipelines.yml: |
{{ required "Logstash pipelines.yml is missing in configuration folder" $pipelinesYaml | indent 4 }}
  xpack.monitoring.enabled: "true"
  xpack.monitoring.elasticsearch.hosts: {{ required "The value global.elasticsearchHosts is missing." .Values.global.elasticsearchHosts | quote }}
  xpack.monitoring.elasticsearch.ssl.certificate_authority: {{ required "The path to the CA for Logstash to Elasticsearch communication is missing" .Values.global.elasticsearchCa | quote }}
  xpack.monitoring.elasticsearch.ssl.verification_mode: {{ default "certificate" .Values.logstash.validateElasticsearchCertificate | quote }}
  LS_JAVA_OPTS: {{ .Values.logstash.logstashJavaOpts | quote }}
  ELASTICSEARCH_HOSTS: {{ required "The value global.elasticsearchHosts is missing." .Values.global.elasticsearchHosts | quote }}
  ELASTICSEARCH_CERT: {{ required "The path to the CA for Logstash to Elasticsearch communication is missing" .Values.global.elasticsearchCa | quote }}
  {{- if eq .Values.logstash.validateElasticsearchCertificate "none" }}
  ELASTICSEARCH_SSL_VERIFICATIONMODE: "false"
  {{- else }}
  ELASTICSEARCH_SSL_VERIFICATIONMODE: "true"
  {{- end }}
  API_BUILDER_URL: "https://{{ include "apim4elastic.fullname" . }}-apibuilder4elastic:{{ .Values.apibuilder4elastic.port }}"
  DROP_TRACE_MESSAGE_LEVELS: {{ .Values.logstash.dropTraceMessageLevels | quote }}
  API_BUILDER_SSL_CERT: {{ required "The path to the CA for Logstash to Elasticsearch communication is missing" .Values.global.elasticsearchCa | quote }}
  MEMCACHED: localhost:11211
  LOG_LEVEL: info
  {{- if .Values.logstash.lookupCacheTTL }}
  LOOKUP_CACHE_TTL: {{ default "" .Values.logstash.lookupCacheTTL | quote }}
  {{- end }}
  CACHE_API_PATHS: {{ default "" .Values.logstash.cacheAPIPaths | quote }}
  GEOIP_ENABLED: {{ default "true" .Values.logstash.geoip.enabled | quote }}
  GEOIP_CACHE_SIZE: {{ default "1000" .Values.logstash.geoip.cacheSize | quote }}
  GEOIP_CUSTOM_ATTRIBUTE: {{ default "true" .Values.logstash.geoip.customAttribute | quote }}
  xpack.geoip.download.endpoint: {{ default "" .Values.logstash.geoip.downloadEndpoint | quote }}
  EVENTLOG_CUSTOM_ATTR: {{ default "" .Values.apibuilder4elastic.eventlogCustomAttributes | quote }}
{{- end }}