{{- if and .Values.logstash.enabled .Values.logstash.logstashSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logstash.fullname" . }}-secret
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
type: Opaque
data:
  LOGSTASH_USERNAME: {{ default "" .Values.logstash.logstashSecrets.logstashUsername | b64enc | quote }}
  LOGSTASH_PASSWORD: {{ default "" .Values.logstash.logstashSecrets.logstashPassword | b64enc | quote }}
  xpack.monitoring.elasticsearch.username: {{ default "" .Values.logstash.logstashSecrets.logstashSystemUsername | b64enc | quote }}
  xpack.monitoring.elasticsearch.password: {{ default "" .Values.logstash.logstashSecrets.logstashSystemPassword | b64enc | quote }}
{{- end }}