# This workflow is validating the API-Builder exposed Traffic-Monitor API. 
# For that an Elasticsearch instance is started, test-data inserted and the 
# API-Builder Traffic-Monitor API is executed with all possible parameters.

name: API-Builder4Elastic tests

on: [push, pull_request]

jobs:
  test-elk-util-flow-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic/custom_flow_nodes/api-builder-plugin-elk-solution-utils'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run npm ci, npm test
      working-directory: ${{env.workingDirectory}}
      env:
        LOG_LEVEL: DEBUG
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test

  apim-util-flow-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic/custom_flow_nodes/api-builder-plugin-axway-api-management'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run npm ci, npm test
      working-directory: ${{env.workingDirectory}}
      env:
        LOG_LEVEL: DEBUG
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test

  traffic-monitor-util-flow-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic/custom_flow_nodes/api-builder-plugin-traffic-monitor-api-utils'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run npm ci, npm test
      working-directory: ${{env.workingDirectory}}
      env:
        LOG_LEVEL: DEBUG
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test

  authorization-plugin:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic/custom_flow_nodes/api-builder-plugin-authorization'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run npm ci, npm test
      working-directory: ${{env.workingDirectory}}
      env:
        LOG_LEVEL: DEBUG
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test

  test-traffic-monitor-api:
    name: Test Traffic-Monitor API
    needs: [test-elk-util-flow-node, apim-util-flow-node, traffic-monitor-util-flow-node, authorization-plugin]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic'

    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        ports: 
          - 9200:9200
          - 9300:9300
        options: -e "discovery.type=single-node"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Sleep 15 seconds to make sure ES is ready
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - name: Show ES Logs
      run: |
        echo "Logs of ES-Service container: ${{ job.services.elasticsearch.id }}"
        docker logs "${{ job.services.elasticsearch.id }}"
    - name: Test API-Builder API
      working-directory: ${{env.workingDirectory}}
      env:
        ELASTICSEARCH_HOSTS: 'http://localhost:9200'
        VALIDATE_CONFIG: false
        ELASTICSEARCH_SSL_VERIFICATIONMODE: false
        LOG_LEVEL: DEBUG
        DISABLE_SETUP_FLOWS: true # Disable Elasticsearch setup flows for the tests.
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test


  push-latest-apibuilder4elastic:
    name: Push latest APIBuilder4Elastic
    needs: [test-traffic-monitor-api]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'apibuilder4elastic'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image (latest)
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: cwiechmann/apibuilder4elastic
        workdir: ${{env.workingDirectory}}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"