name: Test Logstash pipeline

on: [push, pull_request]

jobs:
  logstash:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    services:
      api-builder:
        image: cwiechmann/elk-traffic-monitor-api:latest
        ports: 
          - 8080:8080
        env:
          MOCK_LOOKUP_API: true
          ENABLE_HTTP_PORT: true
      memcached:
        image: memcached:1.6.6-alpine
        ports: 
          - 11211:11211

    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install logstash
      run: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        sudo apt-get install apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
        sudo apt-get update && sudo apt-get install logstash
    - name: Install Logstash-Verifier
      run: |
        wget -c https://github.com/magnusbaeck/logstash-filter-verifier/releases/download/1.6.1/logstash-filter-verifier_1.6.1_linux_amd64.tar.gz -O - | tar -xvz
    - name: Test Logstash pipeline
      run: |
        echo Using API_BUILDER_URL: $API_BUILDER_URL
        echo Using MEMCACHED: $MEMCACHED
        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-tracemessages.json ./logstash/pipelines/TraceMessagesPipeline.conf
        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-events.json ./logstash/pipelines/EventsPipeline.conf
        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-opentrafficlog.json ./logstash/pipelines/OpenTrafficPipeline.conf
        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/filetransfer/test-opentrafficlog-filetransfer.json ./logstash/pipelines/OpenTrafficPipeline.conf

      env:
        API_BUILDER_URL: 'http://localhost:8080'
        MEMCACHED: 'localhost:11211'
        API_BUILDER_SSL_CERT: ""
