name: Logstash pipeline tests

on: [push, pull_request]

jobs:
  logstash:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    services:
      api-builder:
        image: cwiechmann/apibuilder4elastic:latest
        ports: 
          - 8080:8080
        env:
          MOCK_LOOKUP_API: true
          MOCK_API_CREATION: true
          DISABLE_SETUP_FLOWS: true
          LOG_LEVEL: debug
          # The API-Builder doesn't need an Elasticsearch server
          VALIDATE_ELASTIC_CONNECTION: false
          ENABLE_HTTP_PORT: true
          ELASTICSEARCH_HOSTS: http://any.es-host.com:9200
          ELASTICSEARCH_SSL_VERIFICATIONMODE: false
      memcached:
        image: memcached:1.6.6-alpine
        ports: 
          - 11211:11211

    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install logstash
      run: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        sudo apt-get install apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
        sudo apt-get update && sudo apt-get install logstash
    - name: Install Logstash-Verifier
      run: |
        wget -c https://github.com/magnusbaeck/logstash-filter-verifier/releases/download/1.6.3/logstash-filter-verifier_1.6.3_linux_amd64.tar.gz -O - | tar -xvz
    - name: Test Logstash pipeline
      run: |
        echo Using API_BUILDER_URL: $API_BUILDER_URL
        echo Using MEMCACHED: $MEMCACHED
        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-events.json ./logstash/pipelines/EventsPipeline.conf
#      run: |
#        echo Using API_BUILDER_URL: $API_BUILDER_URL
#        echo Using MEMCACHED: $MEMCACHED
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/jms/test-opentrafficlog-jms.json ./logstash/pipelines/OpenTrafficPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/beatsInput/test-index-creation-lookup.json ./logstash/pipelines/BeatsInputPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED --keep-env=DROP_TRACE_MESSAGE_LEVELS ./logstash/test/http/test-tracemessages.json ./logstash/pipelines/TraceMessagesPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-tracemessages-gmt-4.json ./logstash/pipelines/TraceMessagesPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-events.json ./logstash/pipelines/EventsPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/http/test-opentrafficlog.json ./logstash/pipelines/OpenTrafficPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/filetransfer/test-opentrafficlog-filetransfer.json ./logstash/pipelines/OpenTrafficPipeline.conf
#        ./logstash-filter-verifier --diff-command="diff -y" --keep-env=API_BUILDER_SSL_CERT --keep-env=API_BUILDER_URL --keep-env=MEMCACHED ./logstash/test/domainAudit/test-domain-audit-events.json ./logstash/pipelines/DomainAuditPipeline.conf
      env:
        API_BUILDER_URL: 'http://localhost:8080'
        MEMCACHED: 'localhost:11211'
        DROP_TRACE_MESSAGE_LEVELS: 'DEBUG'
        # This is not relevant as we test with HTTP
        # But it's required by Logstash to be a valid certificate
        API_BUILDER_SSL_CERT: "./config/certificates/apibuilder4elastic.crt"
    - name: API-Builder Logs
      if: ${{ always() }}
      run: |
        docker logs "${{ job.services.api-builder.id }}"