# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      workingDirectory: 'elk-traffic-monitor-api'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Starting Elasticsearch instance
      uses: nyaruka/elasticsearch-action@v1
      with:
        elastic version: '7.6.1' 
    - name: Sleep 30 seconds to make sure ES is ready
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - run: npm ci
      working-directory: ${{env.workingDirectory}}
    - run: npm run build --if-present
      working-directory: ${{env.workingDirectory}}
    - run: npm test
      working-directory: ${{env.workingDirectory}}
      env:
        ELASTIC_NODE: 'http://localhost:9200'
        CI: true
