name: "Test Shell scripts"
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Test Metricbeat shell script
        run: bats -r --tap metricbeat